import logoUrl from '../assets/logo.jpg'
import { PARISH_LOCATION, PARISH_NAME } from '../constants/reportTypes'
import { formatReportGeneratedOn } from '../services/reportService'

/** Official system label shown under the church name on every report. */
export const CHURCH_MANAGEMENT_SYSTEM = 'Church Management System'

export const REPORT_FOOTER = {
  endOfReport: 'End of Report',
  preparedByLabel: 'Prepared By:',
  preparedByRole: 'Administrator',
  systemLine: 'Generated by Parish Connect Church Management System',
}

export const REPORT_LOGO_URL = logoUrl

/**
 * Builds the single canonical report document used by Preview, PDF, and Print.
 * Generate the dataset once; pass the same summary + rows into every output.
 *
 * @param {{ summary: object, rows?: object[] }} input
 */
export function buildUnifiedReportDocument({ summary, rows = [] }) {
  if (!summary) {
    throw new Error('Report summary is required.')
  }

  const generated = formatReportGeneratedOn(summary.generatedAt)
  const generatedOn =
    generated.datePart && generated.timePart
      ? `${generated.datePart}, ${generated.timePart}`
      : '—'

  const title = String(summary.reportTitle || 'Sacramental Report')
    .trim()
    .toUpperCase()

  const summaryFields = [
    { label: 'Report Type', value: summary.reportType || '—' },
    { label: 'Year', value: summary.year || '—' },
    { label: 'Month', value: summary.month || '—' },
    { label: 'Minister', value: summary.minister || 'All Ministers' },
    { label: 'Generated By', value: summary.generatedBy || 'Administrator' },
    { label: 'Generated On', value: generatedOn },
    {
      label: 'Total Records',
      value: String(summary.totalRecords ?? rows.length ?? 0),
    },
  ]

  const columns = Array.isArray(summary.columns) ? summary.columns : []

  return {
    header: {
      logoUrl: REPORT_LOGO_URL,
      churchName: summary.parishName || PARISH_NAME,
      systemName: CHURCH_MANAGEMENT_SYSTEM,
      location: PARISH_LOCATION,
    },
    title,
    summaryFields,
    columns,
    rows: Array.isArray(rows) ? rows : [],
    footer: {
      ...REPORT_FOOTER,
      preparedByName: summary.generatedBy || 'Administrator',
    },
    meta: {
      worksheetName: summary.worksheetName || 'Report',
      filePrefix: summary.filePrefix || 'Parish_Report',
      totalRecords: summary.totalRecords ?? rows.length ?? 0,
    },
  }
}
